### ISSUE TITLE
Error building usb-can. 'struct can_frame' has no member named 'len'.

### ISSUE THREAD

**Issue by BlinkRD** [alexmohr/usb-can#43]
Hi there! I'm trying to build usb-can on kernel 5.10.110-30-rockchip-g12ee46f17a0c.
When I run build, I get error: 'struct can_frame' has no member named 'len'.
Unfortunately with this sbc, we're all stuck on the older kernel.
Is there a way to go about fixing this?
I'm trying to run usb-can upon boot so I can communicate between the sbc and a board with a transceiver on the toolhead of my 3d printer!
The SBC in question is Rock5B.
Thank you!

**Comment by alexmohr** [comment]
Hi, have you tried building with the 5.13 or 5.15 branch? They might work for 5.10 too. If not I can look into fixing it but it will be end of the year because I'm on vacation at the moment

**Comment by BlinkRD** [comment]
I haven't tried building for 5.15 branch. I'll try it. If not I'm SoL. Then I'll have to return this adapter and use mcp2515 adapter instead.

**Comment by BlinkRD** [comment]
Doesn't work. Could this be because of the new socketcan version? Why wouldn't len be found in can.h?

**Comment by alexmohr** [comment]
The socket can interface changed a lot over the last few kernel versions. I skipped someintermediate versions because I never tried to target 5.10. 
It can't find Len because the interface doesn't contain it on 5.10 due to the changes.

I think your best choice at the moment is to use a different adapter. I might be able to look into this at the end of December. Bit I'm definitely not able to get to this any earlier.

**Comment by alexmohr** [comment]
It should now work again with 5.10
